# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'BBangmap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	inhibit_all_warnings!

  # Pods for BBangmap

	pod 'Kingfisher', '~> 6.2.1'
	pod 'Moya/RxSwift', '~> 15.0'
	pod 'NMapsMap'
	pod 'RxCocoa', '~> 6.0'
	pod 'RxGesture'
	pod 'SnapKit', '~> 5.0.0'
	pod 'SwiftLint'
	pod 'SwiftKeychainWrapper', '~> 4.0.1'
	pod 'Then'

end

post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
	end
    end
end
